import axios from 'axios';
import Cookies from 'cookies'
import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Meu app</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          home
        </h1>
      </main>
    </div>
  )
}
export async function getServerSideProps({req, res}) {
  console.log("inicio")
  const cookies = new Cookies(req, res)
  const token = cookies.get('token')
  if(token){
    const response = await axios.post('http://localhost:3000/api/checkToken', {
      token: token,
    })
    if(response.data.status){
      cookies.set('token', response.data.token, {
        httpOnly: true
      })
      return { props: {} }
    }    
  }
  return {
    redirect: {
      destination: '/login',
      permanent: false,
    },
  }
  
}
